GET  http://localhost:5555/estados

###

POST http://localhost:5555/estados
Content-Type: application/json

{
    "nome":"Amazonas",
    "sigla":"AM"

}

###
PUT http://localhost:5555/estados
Content-Type: application/json

{   
    "id": 14,
    "nome":"Bahia",
    "sigla":"BA"

}

###
DELETE  http://localhost:5555/estados
Content-Type: application/json

{   
    "id": 15
}

###
POST http://localhost:5555/cidades
Content-Type: application/json

{   
    "nome":"Test cidade",
    "estado_id":7

}

###
GET http://localhost:5555/cidades

###
PUT http://localhost:5555/cidades
Content-Type: application/json

{   
    "id":9,
    "nome":"Teste city",
    "estado_id":"7"

}

###
DELETE  http://localhost:5555/cidades
Content-Type: application/json

{   
    "id": 9
}

###
POST http://localhost:5555/tipos
Content-Type: application/json

{   
    "tipo":"Teste",
    "fator":"Teste Delete"

}

###
GET http://localhost:5555/tipos

###
PUT http://localhost:5555/tipos
Content-Type: application/json

{   
    "id": 10,
    "tipo":"A",
    "fator":"Negativo"

}

###
DELETE  http://localhost:5555/tipos
Content-Type: application/json

{   
    "id": 10
}

###
POST http://localhost:5555/pessoa
Content-Type: application/json

{   
    "nome": "Teste-teste",
    "rua": "Teste",
    "numero": "99",
    "complemento": "Apto 22",
    "rg": "98.765.432",
    "cidade_id": 1,  
    "tipo_id": 1 

}

### 

GET http://localhost:5555/pessoa

###
GET http://localhost:5555/pessoa/nome/Vitor%20Marques/1

###
PUT http://localhost:5555/pessoa
Content-Type: application/json

{   
    "id":6,
    "nome": "Funcinou?",
    "rua": "Teste",
    "numero": "99",
    "complemento": "Apto 22",
    "rg": "98.765.432",
    "cidade_id": 3,  
    "tipo_id": 5 

}

###

DELETE  http://localhost:5555/pessoa
Content-Type: application/json

{   
    "id": 6
}

###
POST http://localhost:5555/locais
Content-Type: application/json

{
    "nome":"Teste",
    "rua":"Teste",
    "numero":"1.468",
    "complemento":"Maruípe, Vitória",
    "cidade_id":4

}

###
GET http://localhost:5555/locais

###
http://localhost:5555/locais/nome/Hospital%20Margarida/1

###
PUT http://localhost:5555/locais
Content-Type: application/json

{   
    "id": 4,
    "nome":"Teste-testinho",
    "rua":"Teste-Teste",
    "numero":"1.468",
    "complemento":"Maruípe, Vitória",
    "cidade_id":1

}

###
DELETE  http://localhost:5555/locais
Content-Type: application/json

{   
    "id": 4
}

###
POST http://localhost:5555/doacoes
Content-Type: application/json

{
    "pessoa_id": 1,
    "local_id": 2,
    "data": "2023-12-16T14:35:00.000Z"


}

###

GET http://localhost:5555/doacoes

###

PUT http://localhost:5555/doacoes
Content-Type: application/json

{   
    "id":4,
    "pessoa_id": 2,
    "local_id": 1,
    "data": "2023-12-16T18:35:00.000Z"

}

###
DELETE  http://localhost:5555/doacoes
Content-Type: application/json

{   
    "id": 4
}